language:       cpp
compiler:       g++
before_install: test/build/depends.sh
script:         test/build/basis.sh
branches:
  only:
    - develop
os:
  - linux
  - osx
env:
#  - prefix=/tmp/local cmake=2.8.12 itk=any  jython=any doxygen=1.8.10 sphinx=any utilities=yes tools=yes example=yes doc=yes tests=yes
#  - prefix=/tmp/local cmake=3.3.1  itk=any  jython=any doxygen=1.8.10 sphinx=any utilities=no  tools=no  example=no  doc=no  tests=no 
#  - prefix=/tmp/local cmake=3.3.1  itk=none jython=none doxygen=1.8.10 sphinx=any utilities=yes tools=yes example=yes doc=no  tests=no 
#  - prefix=/tmp/local cmake=3.3.1  itk=any  jython=any doxygen=1.8.10 sphinx=any utilities=yes tools=yes example=yes doc=no  tests=no 
  - prefix=/tmp/local cmake=3.3.1  itk=any  jython=any doxygen=1.8.10 sphinx=any utilities=yes tools=yes example=yes doc=yes tests=no 
#  - prefix=/tmp/local cmake=3.3.1  itk=any  jython=any doxygen=1.8.10 sphinx=any utilities=yes tools=yes example=no  doc=no  tests=yes
