language: cpp
compiler:
  - g++
before_install:
  - sudo apt-get update
  - sudo apt-get install jython graphviz doxygen python-sphinx libgdcm2-dev libvtkgdcm2-dev libfftw3-dev libvtk5-dev libinsighttoolkit3-dev
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=ON -DBUILD_DOCUMENTATION=ON -DBASIS_ALL_DOC=ON -DBUILD_BASIS_UTILITIES_FOR_CXX=ON -DBUILD_BASIS_UTILITIES_FOR_BASH=ON -DBUILD_BASIS_UTILITIES_FOR_PERL=ON  -DBUILD_BASIS_UTILITIES_FOR_PYTHON=ON ..
  - make
after_success:
  - ctest -C Release
branches:
  only:
    - develop
os:
  - linux
